server:
  port: 1000
  servlet:
    context-path: /source
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: source
  datasource:
    password: cdc@12345
    url: jdbc:sqlserver://localhost;DatabaseName=CHANGE_DATA_CAPTURE;trustServerCertificate=true
    username: cdc_user
